/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.tcc.visao;

import br.edu.ifsp.tcc.controle.ControleEventoColetivo;
import br.edu.ifsp.tcc.controle.ControleObservacao;
import br.edu.ifsp.tcc.modelo.EventoColetivo;
import br.edu.ifsp.tcc.modelo.Observacao;
import br.edu.ifsp.tcc.modelo.Pavilhao;
import br.edu.ifsp.tcc.modelo.Sentenciado;
import java.awt.Font;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author macel
 */
public class CadastroObservacao extends javax.swing.JDialog {

    private ControleObservacao controle = new ControleObservacao();
    private List<Observacao> listObservacao = new ArrayList();
    Observacao f = new Observacao();
    private Sentenciado sentenciado;

    DateFormat df = new SimpleDateFormat("dd/MM/yyyy"); // o mes tem que ser maiusculo
    DateFormat dfh = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss"); // o mes tem que ser maiusculo

    /**
     * Creates new form FormUsuario
     */
    public CadastroObservacao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarLista();
        atualizaTabela();
        TamanhoColuna();
        trataEdicao(false);
    }

    private void trataEdicao(boolean editando) {
        btnCancelar.setEnabled(editando);
        btnSalvar.setEnabled(editando);
        btnExcluir.setEnabled(!editando);
        btnNovo.setEnabled(!editando);
        jDateChooserDataObservacao.setEnabled(editando);
        txtRelato.setEditable(editando);
        // txtLocalizarEventoColetivo.setEditable(editando);
        jTableObservacao.setEnabled(!editando);

    }

    public void TamanhoColuna() {
        jTableObservacao.getColumnModel().getColumn(0).setMaxWidth(100);
        jTableObservacao.getColumnModel().getColumn(1).setMaxWidth(200);
        jTableObservacao.getColumnModel().getColumn(2).setMaxWidth(200);
        jTableObservacao.getColumnModel().getColumn(3).setMaxWidth(700);
        jTableObservacao.setAutoCreateRowSorter(true); // ordena ao clicar na coluna
        JTableHeader jth = jTableObservacao.getTableHeader();
        jth.setFont(new Font("Arial Unicod MS", Font.BOLD, 14));
    }

    public void atualizaTabela() {
        DefaultTableModel dtm = (DefaultTableModel) jTableObservacao.getModel();
        dtm.setNumRows(0);//apagando todas as linhas
        for (Observacao f : listObservacao) {
            dtm.addRow(new Object[]{f.getSentenciado().getMatricula(), df.format(f.getDataRegistro()), dfh.format(f.getDataOcorrido()), f.getRelato()});
        }
    }

    public void carregarLista() {
        listObservacao = controle.buscar();
    }

    public void limparCampos() {
        jDateChooserDataObservacao.setDate(null);
        txtAdicionaMatriculaSentenciado.setText("");
        txtRelato.setText("");

    }

    public void pesquisar() {
        listObservacao.clear();//limpa lista
        DefaultTableModel dtm = (DefaultTableModel) jTableObservacao.getModel();
        dtm.setNumRows(0);//LIMPA A TABELA
        String str = "";
        str = txtLocalizarObservacao.getText();
        if (jcbPesquisarEventoColetivo.getSelectedItem().toString().equals("Matricula")) {
            listObservacao.addAll(controle.listarMatricula(str));//ATUALIZA A LISTA COM OS DADOS DESTA PESQUISA RELEASE
        }
        if (jcbPesquisarEventoColetivo.getSelectedItem().toString().equals("Relato")) {
            listObservacao.addAll(controle.listarRelato(str));//ATUALIZA A LISTA COM OS DADOS DESTA PESQUISA RELEASE
        }
        txtLocalizarObservacao.requestFocus();
        atualizaTabela();//PREENCHE COM OS NOVOS DADOS
    }

    public void vincularCampos() {
        Observacao f = listObservacao.get(jTableObservacao.getSelectedRow());// pega a linha da tabela
        jDateChooserDataObservacao.setDate(f.getDataOcorrido());
        txtRelato.setText(f.getRelato());
        txtAdicionaMatriculaSentenciado.setText(f.getSentenciado().getMatricula());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("PersistenciaPU").createEntityManager();
        queryPavilhao = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("from Pavilhao f order by f.sigla");
        listPavilhao = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryPavilhao.getResultList());
        painelLogin = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRelato = new javax.swing.JTextArea();
        painelTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableObservacao = new javax.swing.JTable();
        txtLocalizarObservacao = new javax.swing.JTextField();
        jcbPesquisarEventoColetivo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jDateChooserDataObservacao = new com.toedter.calendar.JDateChooser();
        jButtonAdicionaSentenciado = new javax.swing.JButton();
        txtAdicionaMatriculaSentenciado = new javax.swing.JTextField();
        painelAcoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Observação");

        painelLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar Observações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel13.setText("Relato:");

        txtRelato.setColumns(20);
        txtRelato.setRows(5);
        txtRelato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRelatoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(txtRelato);

        painelTabela.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar  Observações por:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N
        painelTabela.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableObservacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Data do Registro", "Data da Ocorrencia", "Relato"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableObservacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableObservacaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableObservacao);

        painelTabela.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 71, 840, 150));

        txtLocalizarObservacao.setFont(txtLocalizarObservacao.getFont().deriveFont(txtLocalizarObservacao.getFont().getSize()+3f));
        txtLocalizarObservacao.setEnabled(false);
        txtLocalizarObservacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalizarObservacaoActionPerformed(evt);
            }
        });
        txtLocalizarObservacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLocalizarObservacaoKeyReleased(evt);
            }
        });
        painelTabela.add(txtLocalizarObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 36, 650, -1));

        jcbPesquisarEventoColetivo.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jcbPesquisarEventoColetivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matricula", "Relato" }));
        jcbPesquisarEventoColetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPesquisarEventoColetivoActionPerformed(evt);
            }
        });
        painelTabela.add(jcbPesquisarEventoColetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 35, 168, -1));

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel10.setText("Data  do Ocorrido:");

        jButtonAdicionaSentenciado.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jButtonAdicionaSentenciado.setText("Adicionar Sentenciado");
        jButtonAdicionaSentenciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionaSentenciadoActionPerformed(evt);
            }
        });

        txtAdicionaMatriculaSentenciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdicionaMatriculaSentenciadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLoginLayout = new javax.swing.GroupLayout(painelLogin);
        painelLogin.setLayout(painelLoginLayout);
        painelLoginLayout.setHorizontalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(painelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelLoginLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jDateChooserDataObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButtonAdicionaSentenciado)
                        .addGap(18, 18, 18)
                        .addComponent(txtAdicionaMatriculaSentenciado, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        painelLoginLayout.setVerticalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserDataObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jButtonAdicionaSentenciado)
                        .addComponent(txtAdicionaMatriculaSentenciado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(painelLogin, java.awt.BorderLayout.CENTER);

        painelAcoes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        btnNovo.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/adicionar.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/deletar.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelAcoesLayout = new javax.swing.GroupLayout(painelAcoes);
        painelAcoes.setLayout(painelAcoesLayout);
        painelAcoesLayout.setHorizontalGroup(
            painelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAcoesLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        painelAcoesLayout.setVerticalGroup(
            painelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnNovo)
                .addComponent(btnCancelar)
                .addComponent(btnSalvar)
                .addComponent(btnExcluir))
        );

        getContentPane().add(painelAcoes, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        f = new Observacao();
        trataEdicao(true);
        limparCampos();
        jDateChooserDataObservacao.requestFocus();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        trataEdicao(false);
        limparCampos();
        carregarLista();
        atualizaTabela();
        limparCampos();
        JOptionPane.showMessageDialog(this, "OPERAÇÃO CANCELADA", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        txtLocalizarObservacao.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (jDateChooserDataObservacao.getDate() != null) {
            if (!txtAdicionaMatriculaSentenciado.getText().equals("")) {
                if (!txtRelato.getText().isEmpty()) {
                    f.setDataOcorrido(jDateChooserDataObservacao.getDate());
                    f.setDataRegistro(new Date());
                    f.setRelato(txtRelato.getText().trim());
                    f.setSentenciado(sentenciado);
                    controle.alterar(f);//salvar o orçamento
                    carregarLista();
                    atualizaTabela();
                    limparCampos();
                    trataEdicao(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Relate o Ocorrido!", "Alerta", JOptionPane.WARNING_MESSAGE);
                    txtRelato.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecione o Sentenciado!", "Alerta", JOptionPane.WARNING_MESSAGE);
                txtAdicionaMatriculaSentenciado.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione a data da Observação!", "Alerta", JOptionPane.WARNING_MESSAGE);
            jDateChooserDataObservacao.requestFocus();
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if (jTableObservacao.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha da tabela para excluir", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            if (JOptionPane.showConfirmDialog(null, "Confirma exclusão?",
                    "Exclusão da Observação", JOptionPane.YES_NO_OPTION)
                    == JOptionPane.YES_OPTION) {
                Observacao f = listObservacao.get(jTableObservacao.getSelectedRow());
                controle.remover(f);
            }
        }
        carregarLista();
        atualizaTabela();
        limparCampos();

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtLocalizarObservacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalizarObservacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalizarObservacaoActionPerformed

    private void txtRelatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRelatoMouseClicked
        // TODO add your handling code here:
        vincularCampos();
    }//GEN-LAST:event_txtRelatoMouseClicked

    private void txtLocalizarObservacaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLocalizarObservacaoKeyReleased
        // TODO add your handling code here:
        pesquisar();
    }//GEN-LAST:event_txtLocalizarObservacaoKeyReleased

    private void jcbPesquisarEventoColetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPesquisarEventoColetivoActionPerformed
        // TODO add your handling code here:
        txtLocalizarObservacao.setEnabled(true);
        txtLocalizarObservacao.requestFocus();
    }//GEN-LAST:event_jcbPesquisarEventoColetivoActionPerformed

    private void txtAdicionaMatriculaSentenciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdicionaMatriculaSentenciadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdicionaMatriculaSentenciadoActionPerformed

    private void jTableObservacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableObservacaoMouseClicked
        // TODO add your handling code here:
        vincularCampos();
        jDateChooserDataObservacao.requestFocus();
    }//GEN-LAST:event_jTableObservacaoMouseClicked

    private void jButtonAdicionaSentenciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionaSentenciadoActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        PesquisarSentenciado psent = new PesquisarSentenciado(null, true); /// posso passar usuário
        psent.setVisible(true);
        sentenciado = psent.getSentenciado();
        txtAdicionaMatriculaSentenciado.setText(sentenciado.getMatricula());
    }//GEN-LAST:event_jButtonAdicionaSentenciadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroObservacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroObservacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroObservacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroObservacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroObservacao dialog = new CadastroObservacao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButtonAdicionaSentenciado;
    private com.toedter.calendar.JDateChooser jDateChooserDataObservacao;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableObservacao;
    private javax.swing.JComboBox<String> jcbPesquisarEventoColetivo;
    private java.util.List<Pavilhao> listPavilhao;
    private javax.swing.JPanel painelAcoes;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JPanel painelTabela;
    private javax.persistence.Query queryPavilhao;
    private javax.swing.JTextField txtAdicionaMatriculaSentenciado;
    private javax.swing.JTextField txtLocalizarObservacao;
    private javax.swing.JTextArea txtRelato;
    // End of variables declaration//GEN-END:variables
}
