/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.tcc.visao;

import br.edu.ifsp.tcc.controle.ControleSentenciado;
import br.edu.ifsp.tcc.modelo.Funcionario;
import br.edu.ifsp.tcc.modelo.Sentenciado;
import java.awt.Color;
import java.io.InputStream;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.query.JRJpaQueryExecuterFactory;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author macel
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private Funcionario funcionario;
    private ControleSentenciado controleSentenciado = new ControleSentenciado();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    // Este funcionarío sera usado caso resolva trabalhar por niveis de acesso
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        sbmFuncionario = new javax.swing.JMenuItem();
        sbmSentenciado = new javax.swing.JMenuItem();
        sbmCoordenadoria = new javax.swing.JMenuItem();
        sbmPresidio = new javax.swing.JMenuItem();
        sbmPavilhao = new javax.swing.JMenuItem();
        sbmOcorrencia = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        sbmMovimentacaoInterna = new javax.swing.JMenuItem();
        sbmMovimentacaoExterna = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        sbmSindicancia = new javax.swing.JMenuItem();
        sbmObservacao = new javax.swing.JMenuItem();
        sbmEventoColetivo = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        sbmRelatorioSentenciadoNoPresídio = new javax.swing.JMenuItem();
        sbmRelatorioSentenciadoPorFaccao = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistemas - Tela Principal");
        setExtendedState(6);

        jLabelFundo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/fundo1.jpg"))); // NOI18N
        jLabelFundo.setMinimumSize(new java.awt.Dimension(800, 600));

        menuCadastro.setText("Cadastro");
        menuCadastro.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        menuCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuCadastroMouseEntered(evt);
            }
        });
        menuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroActionPerformed(evt);
            }
        });

        sbmFuncionario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sbmFuncionario.setText("Funcionário");
        sbmFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmFuncionarioActionPerformed(evt);
            }
        });
        menuCadastro.add(sbmFuncionario);

        sbmSentenciado.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        sbmSentenciado.setText("Sentenciado");
        sbmSentenciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmSentenciadoActionPerformed(evt);
            }
        });
        menuCadastro.add(sbmSentenciado);

        sbmCoordenadoria.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        sbmCoordenadoria.setText("Coordenadoria");
        sbmCoordenadoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmCoordenadoriaActionPerformed(evt);
            }
        });
        menuCadastro.add(sbmCoordenadoria);

        sbmPresidio.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        sbmPresidio.setText("Presidio");
        sbmPresidio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmPresidioActionPerformed(evt);
            }
        });
        menuCadastro.add(sbmPresidio);

        sbmPavilhao.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        sbmPavilhao.setText("Pavilhão");
        sbmPavilhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmPavilhaoActionPerformed(evt);
            }
        });
        menuCadastro.add(sbmPavilhao);

        sbmOcorrencia.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        sbmOcorrencia.setText("Facção");
        sbmOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmOcorrenciaActionPerformed(evt);
            }
        });
        menuCadastro.add(sbmOcorrencia);

        jMenuBar1.add(menuCadastro);

        jMenu1.setText("Movimentação");
        jMenu1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N

        sbmMovimentacaoInterna.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        sbmMovimentacaoInterna.setText("Movimentação Internas");
        sbmMovimentacaoInterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmMovimentacaoInternaActionPerformed(evt);
            }
        });
        jMenu1.add(sbmMovimentacaoInterna);

        sbmMovimentacaoExterna.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        sbmMovimentacaoExterna.setText("Movimentação Externas");
        sbmMovimentacaoExterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmMovimentacaoExternaActionPerformed(evt);
            }
        });
        jMenu1.add(sbmMovimentacaoExterna);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Ocorrências");
        jMenu3.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N

        sbmSindicancia.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        sbmSindicancia.setText("Sindicancias");
        sbmSindicancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmSindicanciaActionPerformed(evt);
            }
        });
        jMenu3.add(sbmSindicancia);

        sbmObservacao.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        sbmObservacao.setText("Observações");
        sbmObservacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmObservacaoActionPerformed(evt);
            }
        });
        jMenu3.add(sbmObservacao);

        sbmEventoColetivo.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        sbmEventoColetivo.setText("Eventos Coletivos");
        sbmEventoColetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmEventoColetivoActionPerformed(evt);
            }
        });
        jMenu3.add(sbmEventoColetivo);

        jMenuBar1.add(jMenu3);

        menuRelatorios.setText("Relatorios");
        menuRelatorios.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        menuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatoriosActionPerformed(evt);
            }
        });

        sbmRelatorioSentenciadoNoPresídio.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        sbmRelatorioSentenciadoNoPresídio.setText("Sentenciados no Presídio");
        sbmRelatorioSentenciadoNoPresídio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmRelatorioSentenciadoNoPresídioActionPerformed(evt);
            }
        });
        menuRelatorios.add(sbmRelatorioSentenciadoNoPresídio);

        sbmRelatorioSentenciadoPorFaccao.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        sbmRelatorioSentenciadoPorFaccao.setText("Sentenciado por Facção");
        sbmRelatorioSentenciadoPorFaccao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmRelatorioSentenciadoPorFaccaoActionPerformed(evt);
            }
        });
        menuRelatorios.add(sbmRelatorioSentenciadoPorFaccao);

        jMenuBar1.add(menuRelatorios);

        jMenuSair.setText("Sair");
        jMenuSair.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 584, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        setSize(new java.awt.Dimension(915, 642));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sbmServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmServidorActionPerformed
//     //new DialogDadosServidor().setVisible(true);
//        FormServidor form = new FormServidor(this, true);
//        form.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
//        form.setTitle("Manutenção do Servidor");
//        form.setLocationRelativeTo(null);
//        form.setResizable(false);
//        form.setVisible(true);
    }//GEN-LAST:event_sbmServidorActionPerformed

    private void menuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroActionPerformed

    private void sbmOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmOcorrenciaActionPerformed
        // TODO add your handling code here:
        CadastroFaccao fa = new CadastroFaccao(this, true);
        fa.setVisible(true);
    }//GEN-LAST:event_sbmOcorrenciaActionPerformed

    private void sbmPavilhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmPavilhaoActionPerformed
        // TODO add your handling code here:
        CadastroPavilhao pav = new CadastroPavilhao(this, true);
        pav.setVisible(true);
    }//GEN-LAST:event_sbmPavilhaoActionPerformed

    private void sbmPresidioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmPresidioActionPerformed
        // TODO add your handling code here:
        CadastroPresidio pre = new CadastroPresidio(this, true);
        pre.setVisible(true);
    }//GEN-LAST:event_sbmPresidioActionPerformed

    private void sbmCoordenadoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmCoordenadoriaActionPerformed
        // TODO add your handling code here:
        CadastroCoordenadoria c = new CadastroCoordenadoria(this, true);
        c.setVisible(true);
    }//GEN-LAST:event_sbmCoordenadoriaActionPerformed

    private void sbmSentenciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmSentenciadoActionPerformed
        // TODO add your handling code here:
        CadastroSentenciado f = new CadastroSentenciado(this, true);
        f.setVisible(true);

    }//GEN-LAST:event_sbmSentenciadoActionPerformed

    private void sbmFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmFuncionarioActionPerformed
        // TODO add your handling code here:
        CadastroFuncionario c = new CadastroFuncionario(this, true);
        c.setVisible(true);
    }//GEN-LAST:event_sbmFuncionarioActionPerformed

    private void sbmSindicanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmSindicanciaActionPerformed
        // TODO add your handling code here:
        CadastroSindicancia fs = new CadastroSindicancia(this, true);
        fs.setVisible(true);
    }//GEN-LAST:event_sbmSindicanciaActionPerformed

    private void sbmObservacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmObservacaoActionPerformed
        // TODO add your handling code here:
        CadastroObservacao fo = new CadastroObservacao(this, true);
        fo.setVisible(true);
    }//GEN-LAST:event_sbmObservacaoActionPerformed

    private void sbmEventoColetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmEventoColetivoActionPerformed
        // TODO add your handling code here:
        CadastroEventoColetivo fec = new CadastroEventoColetivo(this, true);
        fec.setVisible(true);
    }//GEN-LAST:event_sbmEventoColetivoActionPerformed

    private void sbmMovimentacaoInternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmMovimentacaoInternaActionPerformed
        // TODO add your handling code here:
        CadastroMovimentacaoInterna c = new CadastroMovimentacaoInterna(this, true);
        c.setVisible(true);
        //menuCadastro.setBackground(Color.red);
    }//GEN-LAST:event_sbmMovimentacaoInternaActionPerformed

    private void menuCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCadastroMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroMouseEntered

    private void sbmMovimentacaoExternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmMovimentacaoExternaActionPerformed
        // TODO add your handling code here:
        CadastroMovimentacaoExterna c = new CadastroMovimentacaoExterna(this, true);
        c.setVisible(true);
    }//GEN-LAST:event_sbmMovimentacaoExternaActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jMenuSairActionPerformed

    private void sbmRelatorioSentenciadoNoPresídioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmRelatorioSentenciadoNoPresídioActionPerformed
        try {
            // Carrega o relatório (jrxml)
            JasperDesign jd = JRXmlLoader.load(getClass().
                    getResourceAsStream("/br/edu/ifsp/tcc/relatorio/"
                            + "relatorio-sentenciado-ativos.jrxml"));
            //Copila o relátório e gera o jasper
            JasperReport jr = JasperCompileManager.compileReport(jd);

            HashMap<String, Object> parametros = new HashMap<>();
            parametros.put(JRJpaQueryExecuterFactory.PARAMETER_JPA_ENTITY_MANAGER,
                    this.controleSentenciado.getEntityManager());
            // prepara o relatório em modo de visualização
            JasperPrint jp = JasperFillManager.fillReport(jr, parametros);

            new JasperViewer(jp, false).setVisible(true);

        } catch (JRException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_sbmRelatorioSentenciadoNoPresídioActionPerformed

    private void sbmRelatorioSentenciadoPorFaccaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmRelatorioSentenciadoPorFaccaoActionPerformed
        try {
            // TODO add your handling code here:
            InputStream relatorioJasper = (getClass().getResourceAsStream("/br/edu/ifsp/tcc/relatorio/"
                    + "relatorio-sentenciado-ativos-faccao.jasper"));

            HashMap<String, Object> parametros = new HashMap<>();
            parametros.put(JRJpaQueryExecuterFactory.PARAMETER_JPA_ENTITY_MANAGER,
            this.controleSentenciado.getEntityManager());

            // prepara o relatório em modo de visualização
            JasperPrint jp = JasperFillManager.fillReport(relatorioJasper, parametros);
            // exibe o relatório
            new JasperViewer(jp, false).setVisible(true);
        } catch (JRException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_sbmRelatorioSentenciadoPorFaccaoActionPerformed


    
    private void menuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatoriosActionPerformed
        // TODO add your handling code here:
        try {
//             List<Sentenciado> lista =  this.controleSentenciado.buscar();
//              JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(lista);
//             
//               InputStream relatorioJasper = (getClass().getResourceAsStream("/br/edu/ifsp/tcc/relatorio/"
//                    + "relatorio-sentenciado-ativos.jasper"));
//
//            HashMap<String, Object> parametros = new HashMap<>();
//            parametros.put(JRJpaQueryExecuterFactory.PARAMETER_JPA_ENTITY_MANAGER,
//            this.controleSentenciado.getEntityManager());
//
//            // prepara o relatório em modo de visualização
//            JasperPrint jp = JasperFillManager.fillReport(relatorioJasper, parametros);
//            // exibe o relatório
//            new JasperViewer(jp, false).setVisible(true);
              
              
        } catch (Exception e) {
        }
             
    }//GEN-LAST:event_menuRelatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem sbmCoordenadoria;
    private javax.swing.JMenuItem sbmEventoColetivo;
    private javax.swing.JMenuItem sbmFuncionario;
    private javax.swing.JMenuItem sbmMovimentacaoExterna;
    private javax.swing.JMenuItem sbmMovimentacaoInterna;
    private javax.swing.JMenuItem sbmObservacao;
    private javax.swing.JMenuItem sbmOcorrencia;
    private javax.swing.JMenuItem sbmPavilhao;
    private javax.swing.JMenuItem sbmPresidio;
    private javax.swing.JMenuItem sbmRelatorioSentenciadoNoPresídio;
    private javax.swing.JMenuItem sbmRelatorioSentenciadoPorFaccao;
    private javax.swing.JMenuItem sbmSentenciado;
    private javax.swing.JMenuItem sbmSindicancia;
    // End of variables declaration//GEN-END:variables
}
